NORTH = (0, 1)
EAST = (1, 0)
SOUTH = (0, -1)
WEST = (-1, 0)
NORTH_EAST = (1, 1)
SOUTH_EAST = (-1, 1)
NORTH_WEST = (1, -1)
SOUTH_WEST = (-1, -1)

CARDINAL = [NORTH, EAST, SOUTH, WEST]
CARDINAL_DIAG = CARDINAL + [NORTH_EAST, SOUTH_EAST, NORTH_WEST, SOUTH_WEST]
