[package]
name        = "aoc2021"
version     = "0.1.0"
edition     = "2021"
default-run = "aoc2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono    = "0.4"
num       = "0.4"
itertools = "0.8.2"
